### ISSUE TITLE
error 500 when create new project

### ISSUE THREAD

**Issue by samlouis23** [husomichael/NFT-Randomizer#2]
Good afternoon,
First thanks to share your sources. I'm a student too and  I like to learn from your app.
I tried to follow your Readme on my computer but unfortunately when i try to create a project I have this errors :
- in chrome: 
```
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
project.saga.js:15 addProject catch error: Error: Request failed with status code 500
    at createError (bundle.js:33332:15)
    at settle (bundle.js:33562:12)
    at XMLHttpRequest.onloadend (bundle.js:32743:7)
```

in the server terminal : 
 ```
at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 107,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '18',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1384',
  routine: 'parserOpenTable'
}
```

I followed your instructions
nft_randomizer database has the correct name ok
And inside the database i can see my user well created.

Thanks a lot for your help
regards,
Sam

**Comment by husomichael** [comment]
Are there any more lines above that in the server terminal? Is there an error title?

**Comment by samlouis23** [comment]
```
/projects POST err: error: column "is_current" of relation "projects" does not exist
    at Parser.parseErrorMessage (/Users/spag/Desktop/NFT-Randomizer/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/Users/spag/Desktop/NFT-Randomizer/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/Users/spag/Desktop/NFT-Randomizer/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/Users/spag/Desktop/NFT-Randomizer/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:390:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:199:23) {
  length: 131,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '57',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '1066',
  routine: 'checkInsertTargets'
}
```

**Comment by husomichael** [comment]
Ah there we go. Looks like I didn't update my SQL file.

The "projects" table has another row that I added to it. Here's the updated SQL for that table:

CREATE TABLE "projects" (
  "id" SERIAL PRIMARY KEY,
  "project_name" VARCHAR(120) NOT NULL,
  "is_current" BOOLEAN,
  "user_id"  INT REFERENCES "user" ON DELETE CASCADE
);

**Comment by samlouis23** [comment]
Well spotted: it works !
Thank you
